"""!wx — current measurements from a TAWES station of GeoSphere Austria.

Source: dataset.api.hub.geosphere.at, dataset `tawes-v1-10min`, free to use
under CC BY 4.0. The place-to-station mapping lives in `data/stations_ktn.json`
and was generated from GeoSphere's station list (nearest station). The place
names themselves come from OpenStreetMap (ODbL) and are generated by
`tools/build_orte.py`: Carinthia has 34 weather stations but three thousand
places — someone standing in Knappenberg types "Knappenberg", not "Friesach".
"""

from __future__ import annotations

import json
import math
import re
from difflib import get_close_matches
from typing import Any

import httpx

from ..config import Settings
from .sota import parse_coords

# Parenthesised suffixes are not part of the place: to whoever is asking, the
# station "Klagenfurt-Flughafen (Automat)" is simply Klagenfurt-Flughafen.
KLAMMER = re.compile(r"\s*\([^)]*\)")

PARAMS = "TL,RF,FFAM,DD,P"          # temperature, humidity, wind, direction, pressure
HIMMELSRICHTUNG = ["N", "NO", "O", "SO", "S", "SW", "W", "NW"]

# Real places that exist -- just not here. They have to be caught **before**
# the similarity search, otherwise a Carinthian hamlet with a similar name wins:
# "Hamburg" became "Haimburg", "Lienz" became "Lienze".
#
# Why a list and not a stricter threshold: there is none. Measured against real
# cases the similarity scores overlap completely -- `hamburg -> haimburg` scores
# 0.933 and is therefore **higher** than the genuine typo `vilach -> villach`
# (0.923). Any threshold that locks Hamburg out also locks out "vilach",
# "goldek" and "spittall". That Hamburg is a real place outside Carinthia is not
# in the string -- that is knowledge, and knowledge belongs in a table.
AUSSERHALB = {
    "wien", "graz", "linz", "salzburg", "innsbruck", "bregenz", "eisenstadt",
    "st poelten", "lienz", "kitzbuehel", "kufstein", "zell am see", "schladming",
    "hamburg", "berlin", "muenchen", "stuttgart", "frankfurt", "koeln", "dresden",
    "zuerich", "bern", "basel", "genf", "ljubljana", "maribor", "bled", "jesenice",
    "triest", "trieste", "udine", "tarvis", "tarvisio", "venedig", "mailand", "rom",
    "budapest", "prag", "bratislava", "muenchen", "london", "paris", "madrid",
}


def _richtung(grad: float | None) -> str:
    if grad is None:
        return ""
    return HIMMELSRICHTUNG[int((grad % 360) / 45 + 0.5) % 8]


def load_stations(settings: Settings) -> dict[str, Any]:
    """Place mapping and the full station list.

    The place mapping covers the common names; the station list enables lookup
    by coordinates — nobody types a place name on a mountain, but the device
    knows the position.
    """
    with open(settings.stations_file, encoding="utf-8") as fh:
        daten = json.load(fh)
    if "orte" not in daten:            # altes Format ohne Stationsliste
        return {"orte": daten, "stationen": []}
    return daten


def distanz_km(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    r = 6371.0
    p1, p2 = math.radians(lat1), math.radians(lat2)
    dp = p2 - p1
    dl = math.radians(lon2 - lon1)
    a = math.sin(dp / 2) ** 2 + math.cos(p1) * math.cos(p2) * math.sin(dl / 2) ** 2
    return 2 * r * math.asin(math.sqrt(a))


def station_bei(stationen: list[dict[str, Any]], lat: float, lon: float) -> dict[str, Any] | None:
    """Nearest weather station to a position."""
    if not stationen:
        return None
    return min(stationen, key=lambda s: distanz_km(lat, lon, s["lat"], s["lon"]))


def normalisiere(name: str) -> str:
    """Bring a place name into the directory's spelling.

    Must match `tools/build_orte.py`, otherwise the key will not find its entry.
    Dots and hyphens are dropped so that "St.Veit", "St-Veit" and "Sankt Veit"
    all land on "st veit". The slash is known only to this side: in the
    directory it splits bilingual names into two entries, in a query it is a
    typo.
    """
    s = KLAMMER.sub("", " ".join(name.split())).lower()
    for alt, neu in (("ö", "oe"), ("ä", "ae"), ("ü", "ue"), ("ß", "ss"),
                     ("š", "s"), ("č", "c"), ("ž", "z"),
                     (".", " "), ("-", " "), ("/", " "), ("'", ""), ("`", "")):
        s = s.replace(alt, neu)
    # "Bad Sankt Leonhard" and "Bad St. Leonhard" are the same place.
    return " ".join("st" if w == "sankt" else w for w in s.split())


def resolve_place_stufe(arg: str, stations: dict[str, Any], default: str,
                        fuzzy: bool = True) -> tuple[str, dict[str, Any], str] | None:
    """Like `resolve_place`, but says **how certain** the match is.

    The stage is `exakt`, `koord` or `geraten`. Only the first two are
    knowledge; `geraten` is a guess from the similarity search and is marked as
    such in the answer. Without that distinction a guessed answer looks exactly
    like a known one — which is precisely how "Hamburg" slipped through as
    Haimburg.
    """
    orte = stations.get("orte", stations)

    koord = parse_coords(arg)
    if koord is not None:
        s = station_bei(stations.get("stationen", []), *koord)
        if s is not None:
            return s["name"], {"station_id": s["id"], "station": s["name"],
                               "lat": s["lat"], "lon": s["lon"]}, "koord"
        return None

    key = normalisiere(arg) or normalisiere(default)
    if key in orte:
        return key, orte[key], "exakt"
    # With three thousand place names, a loose threshold finds some hamlet for
    # every typo. 0.8 lets "vilach" through and "xyz" not.
    if not fuzzy:
        return None
    # Do not let known out-of-coverage places reach the guessing stage at all.
    if key in AUSSERHALB:
        return None
    treffer = get_close_matches(key, list(orte), n=1, cutoff=0.8)
    if treffer:
        return treffer[0], orte[treffer[0]], "geraten"
    return None


def resolve_place(arg: str, stations: dict[str, Any], default: str,
                  fuzzy: bool = True) -> tuple[str, dict[str, Any]] | None:
    """Map a place or position to a station.

    Accepts a place name (with typo tolerance) or coordinates in any notation.
    For coordinates the nearest station is used and its name returned — so the
    receiver can see where the values came from.

    `fuzzy=False` turns the similarity search off. `!wx` needs that now that it
    also knows summits: "Hochstein" is a mountain, but at 0.8 similarity also
    the hamlet "Hohenstein". An **exact** summit match must come before a
    **guessed** place match.
    """
    treffer = resolve_place_stufe(arg, stations, default, fuzzy)
    return None if treffer is None else (treffer[0], treffer[1])


async def fetch(client: httpx.AsyncClient, settings: Settings, station_id: str) -> dict[str, Any]:
    resp = await client.get(
        settings.geosphere_tawes_url,
        params={"parameters": PARAMS, "station_ids": station_id, "output_format": "geojson"},
    )
    resp.raise_for_status()
    data = resp.json()
    props = data["features"][0]["properties"]["parameters"]
    return {name: (props.get(name) or {}).get("data", [None])[0] for name in PARAMS.split(",")}


# Answers for a place that does not exist. Chosen by the digit sum of the
# query, not at random: the same typo always gets the same answer, which stays
# reproducible and reads less like a machine rolling dice.
SPOTT = [
    "{ort}? 🧐 Kenn i ned. Da war die Landkarte schneller: !wx villach",
    "{ort} 🗺️❓ Keiner von 3199 Orten. Probier: !wx villach",
    "{ort}? 🤨 Nie gehoert. Tipp: einen Ort in Kaernten waehlen",
    "{ort} 🫠 gibt's ned. Nochmal, diesmal mit Ort: !wx spittal",
    "{ort}? 🔍🤷 Nix gfunden. Position geht immer: !wx 46.61 13.85",
]

# Places that avowedly do not exist. Anyone typing these did not make a typo,
# they made a joke — and a joke may be returned.
SPEZIAL = {
    "hintertupfing": "Hintertupfing 🙄🏚️🐄 Erfunden. Wie deine Ortskenntnis. Nimm Villach",
    "kleinkleckersdorf": "Kleinkleckersdorf 🙄🐓 Auch beim dritten Versuch erfunden",
    "bielefeld": "Bielefeld 🛸🤫 Gibt's bekanntlich ned. Falscher Bot fuer Verschwoerungen",
    "entenhausen": "Entenhausen 🦆💰 Wetter dort: Comic. Hier: Kaernten",
    "absurdistan": "Absurdistan 🤡🌍 Liegt knapp ausserhalb unserer 34 Stationen",
    "timbuktu": "Timbuktu 🐪🏜️ 4700 km zu weit. Kaernten faengt bei Villach an",
    "walachei": "Walachei 🐺🌲 Nicht mal die Karawanken sind so weit weg",
    "mordor": "Mordor 🌋👁️ Ein Ort geht ned einfach so hinein. Nimm !wx villach",
    "nirgendwo": "Nirgendwo 🕳️🤷 Genau dort ist auch deine Wetterstation",
    "buxtehude": "Buxtehude 🐕🐰 Liegt 900 km nordwestlich. Knapp daneben",
}


def render_unbekannt(arg: str) -> str:
    """The place is not in the directory.

    Costs the same airtime as the old refusal `WX: <place> unbekannt`, but also
    says how to do it right — otherwise it would be mockery without use.
    """
    ort = " ".join(arg.split())[:20] or "Nix"
    key = normalisiere(ort)
    if key in SPEZIAL:
        return "WX: " + SPEZIAL[key]
    # A real place, just the wrong one. That deserves a different answer than a
    # typo: someone typing "Hamburg" did not mistype anything.
    if key in AUSSERHALB:
        return f"WX: {ort.title()} liegt ned in Kaernten. 34 Stationen, alle da"
    # Choose on the normalised form, otherwise "villagh" gets a different answer
    # than "Villagh" — the same typo should stay the same typo.
    return "WX: " + SPOTT[sum(key.encode()) % len(SPOTT)].format(ort=ort.title())


def render(ort: str, werte: dict[str, Any], stale: bool = False,
           station: str | None = None, geraten: bool = False,
           anzeige: str | None = None) -> str:
    """One line, fixed order: temperature, humidity, wind, pressure.

    If the station sits somewhere other than the place asked for, it is named.
    Nobody measures in Knappenberg — the values come from Friesach, and that has
    to be stated, or somebody takes it for a measurement on their doorstep.

    `geraten` appends a question mark to the place name. One character, and the
    answer stops claiming to know: `WX Villach?: 21C` reads as "I assume you
    mean Villach". Before this, a guessed answer was indistinguishable from a
    known one.
    """
    marker = "~" if stale else ""
    # `anzeige` is the original spelling from OSM ("Nötsch im Gailtal"), the key
    # is the umlaut-free lookup form. If it is missing -- old file, or name and
    # key are identical anyway -- the key will do.
    kopf = (anzeige or ort.title()) + ("?" if geraten else "")
    if station and normalisiere(station) != normalisiere(anzeige or ort):
        kopf = f"{kopf} ({station})"
    teile = [f"WX {kopf}: {marker}"]
    if werte.get("TL") is not None:
        teile.append(f"{werte['TL']:.1f}C")
    if werte.get("RF") is not None:
        teile.append(f"{werte['RF']:.0f}%")
    if werte.get("FFAM") is not None:
        kmh = werte["FFAM"] * 3.6
        teile.append(f"Wind {kmh:.0f}km/h {_richtung(werte.get('DD'))}".strip())
    if werte.get("P") is not None:
        teile.append(f"{werte['P']:.0f}hPa")
    return teile[0] + ", ".join(teile[1:])
